
CREATE TABLE FC_USER(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASS VARCHAR(255)
);

INSERT INTO FC_USER (USERNAME, PASS) VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918');



CREATE TABLE FC_WORD(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WORD VARCHAR(255),
    MEANING VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
    CREATEDATE DATETIME,
    CORRECT_COUNT int,
    WRONG_COUNT int,
    UNIQUE (WORD)
);



CREATE TABLE FC_SESSION(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CREATEDATE DATETIME,
    IS_DONE TINYINT(1)
);


CREATE TABLE FC_SESSION_WORD(
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID BIGINT NOT NULL,
    WORD_ID BIGINT NOT NULL
);

CREATE INDEX FC_SESSION_WORD_IDX ON FC_SESSION_WORD ( SESSION_ID, ID);  