## Not Working for selinux reason
## should run init.sh
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: php_workspace
  name: php_workspace
spec:
  containers:
  - name: nginx
    image: docker.io/nginx:latest
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-confd
    - mountPath: /app
      name: php-scripts
    ports:
    - containerPort: 80
      hostPort: 8090
      protocol: TCP
  - name: php
    image: docker.io/library/php:fpm
    volumeMounts:
    - mountPath: /app
      name: php-scripts
  volumes:
  - hostPath:
      path: /home/alireza/Documents/podman-containers/php-mysql-nginx/scripts
      type: Directory
    name: php-scripts
  - hostPath:
      path: /home/alireza/Documents/podman-containers/php-mysql-nginx/nginx-cnfd
      type: Directory
    name: nginx-confd